### ISSUE TITLE
SRP Browser throwing errors

### ISSUE THREAD

**Issue by Nabeel-Ash** [Adobe-Marketing-Cloud/aem-communities-srp-browser#1]
The SRP Browser UI fails to load. error.log throws below error. Basically the minification of srp-tools.js is failing. I am using 6.2 SP1. Is any hotfix needs to be installed to get the tool working? 

14.04.2017 10:43:01.423 *ERROR* [132.174.139.184 [1492180981394] GET /etc/clientlibs/srp-tools.min.js HTTP/1.1] com.adobe.granite.ui.clientlibs.impl.YUIScriptProcessor
[ERROR] 4722:26:missing variable name
14.04.2017 10:43:01.423 *ERROR* [132.174.139.184 [1492180981394] GET /etc/clientlibs/srp-tools.min.js HTTP/1.1] com.adobe.granite.ui.clientlibs.impl.YUIScriptProcessor
[ERROR]                 var final = path.substr(path.lastIndexOf('/') + 1);
14.04.2017 10:43:01.423 *ERROR* [132.174.139.184 [1492180981394] GET /etc/clientlibs/srp-tools.min.js HTTP/1.1] com.adobe.granite.ui.clientlibs.impl.YUIScriptProcessor
[ERROR] 4723:59:identifier is a reserved word
14.04.2017 10:43:01.423 *ERROR* [132.174.139.184 [1492180981394] GET /etc/clientlibs/srp-tools.min.js HTTP/1.1] com.adobe.granite.ui.clientlibs.impl.YUIScriptProcessor
[ERROR]                 var newNode = this.createNode({text: final, nodes: [], count: 0, color: this.ugcNodeColor, type: "UGC", path:json.children[i].path });
14.04.2017 10:43:01.424 *ERROR* [132.174.139.184 [1492180981394] GET /etc/clientlibs/srp-tools.min.js HTTP/1.1] com.adobe.granite.ui.clientlibs.impl.YUIScriptProcessor
[ERROR] 1:0:Compilation produced 10 syntax errors.
14.04.2017 10:43:01.424 *ERROR* [132.174.139.184 [1492180981394] GET /etc/clientlibs/srp-tools.min.js HTTP/1.1] com.adobe.granite.ui.clientlibs.impl.YUIScriptProcessor
[ERROR] null
14.04.2017 10:43:01.424 *ERROR* [132.174.139.184 [1492180981394] GET /etc/clientlibs/srp-tools.min.js HTTP/1.1] com.adobe.granite.ui.clientlibs.impl.HtmlLibraryManagerImpl Error during assembly of library.
org.mozilla.javascript.EvaluatorException: Compilation produced 10 syntax errors.
        at com.adobe.granite.ui.clientlibs.impl.YUIScriptProcessor$1.runtimeError(YUIScriptProcessor.java:145)
        at org.mozilla.javascript.Parser.parse(Parser.java:396)
        at org.mozilla.javascript.Parser.parse(Parser.java:340)
        at com.yahoo.platform.yui.compressor.JavaScriptCompressor.parse(JavaScriptCompressor.java:315)
        at com.yahoo.platform.yui.compressor.JavaScriptCompressor.<init>(JavaScriptCompressor.java:536)
        at com.adobe.granite.ui.clientlibs.impl.YUIScriptProcessor.minifyJS(YUIScriptProcessor.java:121)
        at com.adobe.granite.ui.clientlibs.impl.YUIScriptProcessor.process(YUIScriptProcessor.java:116)
        at com.adobe.granite.ui.clientlibs.impl.AbstractBuilder.build(AbstractBuilder.java:86)

**Comment by LucaMele** [comment]
Same issue using a minified bundle from webpack

**Comment by zetekla** [comment]
Same issue using a bundle compiled from ES6 to ES5 by Browserify. Is AEM rejecting support on new standard JS?

**Comment by justinedelson** [comment]
@zetekla @LucaMele I'm not sure what your issues have to do with the SRP browser.

In general, the YUI compressor has issues with some newer JS constructs. The general approach is to use the GCC compiler instead. If you have trouble with this, I'd suggest working with Adobe support instead of commenting on issues in this project, which is specifically about the SRP browser for AEM communities.
